name: Close Issue on Defect Completion
on:
  repository_dispatch
jobs:
  close-agileplace-issue:
    environment: Team Charlie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: close-issue-check
        if: github.event.action != 'close-ap-issue'
        run: echo "${{toJSON(github)}}"
        
      - name: close-issue
        uses:
          PVSCDemo/ap-actions/close-ap-issue@e291c9d1942499f295bb0e3c606047a76ed70366
        with:
          token: a token
          repository: ${{github.repository}}
          stuff: stuff
