name: Close Issue on Defect Completion
on:
  repository_dispatch
jobs:
  close-agileplace-issue:
    environment: Team Charlie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: close-issue-check
        if: github.event.action != 'close-ap-issue'
        run: echo "${{toJSON(github)}}"
        
      - name: close-issue
        if: github.event.action == 'close-ap-issue'
        uses:
          PVSCDemo/ap-actions/close-ap-issue@fe24af8c16a91203178e98e3ddce264aa6ab0938
        with:
          token:  ${{secrets.GH_TOKEN}}
          repository: ${{github.repository}}
          data: ${{toJSON(github.event.client_payload)}}
          
