name: Close Issue on Defect Completion
on:
  repository_dispatch
jobs:
  close-agileplace-issue:
    environment: Team Charlie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: close-issue
        if: github.event.action == 'close-ap-issue'
        uses:
          PVSCDemo/ap-actions/close-ap-issue@4bb190f41199b73d09790d126ed0ab08eb9eaaf1
        with:
          token:  ${{secrets.GH_TOKEN}}
