name: Close Issue on Defect Completion
on:
  repository_dispatch
jobs:
  close-agileplace-issue:
    environment: Team Charlie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: close-issue
        if: github.event.action == 'close-ap-issue'
        uses:
          PVSCDemo/ap-actions/close-ap-issue@88c4ebbfb9875b71f3364245bd040946dc380faa
        with:
          token:  ${{secrets.GH_TOKEN}}
