on:
  repository_dispatch
  
jobs:
  close-agileplace-issue:
    runs-on: ubuntu-latest
    steps:
      - name: close-it
        uses: PVSCDemo/close-ap-issue@caff743a569db4b8d9184df94231d14ce7a4c34b
        with:
          payload: ${{github.event.client_payload}}
