name: Close Issue on Defect Completion
on:
  repository_dispatch
jobs:
  close-agileplace-issue:
    environment: Team Charlie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: close-issue
        uses:
          PVSCDemo/ap-actions/close-ap-issue@fd35c8c20b854eb6d32d3b34bcd846472b8a78a0
        with:
          token: ${{secrets.GH_TOKEN}}
          repository: ${{github.env.repository}}
          payload: ${{github.event.client_payload}}
