name: Close Issue on Defect Completion
on:
  repository_dispatch
jobs:
  close-agileplace-issue:
    environment: Team Charlie
    runs-on: ubuntu-latest
    steps:
      - name: close-it
        uses: PVSCDemo/close-ap-issue@34a3e969a6a6bc4816e7ac721ff71b7294b2b9df
        with:
          token: ${{secrets.GH_TOKEN}}
          repository: ${{github.env.repository}}
          payload: ${{github.event.client_payload}}
