name: Close Issue on Defect Completion
on:
  repository_dispatch
jobs:
  close-agileplace-issue:
    environment: Team Charlie
    runs-on: ubuntu-latest
    steps:
      - name: close-issue
        uses: 
          actions/checkout@v3
          PVSCDemo/ap-actions/close-ap-issue@b93dbcc78119510de5cfff1b483a0580a3995963
        with:
          token: ${{secrets.GH_TOKEN}}
          repository: ${{github.env.repository}}
          payload: ${{github.event.client_payload}}
