name: Defect Creation in LK
on:
  issues:
    types:
    - opened
jobs:
  create-defect:
    environment: Team Charlie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create defect
        uses: PVSCDemo/github-actions/createCard@v1.1.3
        with:
          host: ${{secrets.LEANKIT_URL}}
          apiToken: ${{secrets.LEANKIT_API}}
          boardId: ${{secrets.BOARD_ID}}
          laneId: ${{secrets.LANE_ID}}
          title: ${{github.event.issue.title}}
          customId: ${{github.event.repository.name}} ${{github.event.issue.number}}
          externalLink: ${{github.event.issue.html_url}}
          typeId: ${{secrets.DEFECT_TYPE}}
      - name: label issue
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: Defect@${{env.createdCardId}}
          repo-token: ${{ secrets.GH_TOKEN }}
