name: Defect Creation in LK
on:
  issues:
    types:
    - opened
jobs:
  create-defect:
    environment: Team Charlie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: createdefect
        uses: PVSCDemo/github-actions/createCard@v1.1.3
        with:
          host: ${{secrets.LEANKIT_URL}}
          apiToken: ${{secrets.LEANKIT_API}}
          boardId: ${{secrets.BOARD_ID}}
          laneId: ${{secrets.LANE_ID}}
          title: ${{github.event.issue.title}}
          customId: ${{github.event.repository.name}} ${{github.event.issue.number}}
          externalLink: ${{github.event.issue.html_url}}
          typeId: ${{secrets.DEFECT_TYPE}}
      - id: labelissue
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: Defect ${{steps.createdefect.outputs.createdCardId}}
          repo-token: ${{ secrets.GH_TOKEN }}
      - id: commentissue
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Agile Place Defect Created
            "https://${{secrets.LEANKIT_URL}/card/${{steps.createdefect.outputs.createdCardId}}"
