name: Defect Creation in LK

on:
  issues:
    types:
    - opened
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-defect:
    environment: Team Charlie
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create defect
        uses: leankit/github-actions/createCard@v1.1
        with:
          host: https://scdemo320.leankit.com
          apiToken: ${{secrets.SCDEMO320}}
          boardId: ${{secrets.BOARDID
          title: ${{github.event.issue.title}} \n (GH:${{github.event.issue.html_url}})
          typeId: ${{secrets.DEFECT_TYPE}}
