name: Defect Creation in LK

on:
  issues:
    types:
    - opened
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-defect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print github info
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
